Repository quay/quay-docs, pull requests merged in 2023-06, with the labels that each got.

#683 Adds known issue fix to 39 RNs
  modules/proc_manage-ldap-setup.adoc
  modules/rn_3_90.adoc
Labels: redhat-3.9

#684 Moves CSO and other content for Operator book
  config_quay/docinfo.xml
  config_quay/master.adoc
  deploy_red_hat_quay_operator/master.adoc
  modules/config-custom-ssl-certs-kubernetes.adoc
  modules/config-fields-legacy.adoc
  modules/config-fields-optional-intro.adoc
  modules/config-preconfigure-automation.adoc
  modules/first-user-api.adoc
  modules/operator-components-unmanaged.adoc
  modules/operator-config-ui-monitoring.adoc
  modules/operator-config-ui-updated.adoc
  modules/operator-deploy-hpa.adoc
  modules/operator-deploy-view-pods-cli.adoc
  modules/operator-deploy.adoc
  modules/operator-first-user-ui.adoc
  modules/operator-helm-oci.adoc
  modules/operator-quayregistry-status.adoc
  modules/operator-standalone-object-gateway.adoc
  modules/operator-unmanaged-hpa.adoc
  modules/operator-unmanaged-mirroring.adoc
  modules/operator-unmanaged-monitoring.adoc
  modules/operator-unmanaged-redis.adoc
  modules/operator-unmanaged-route.adoc
  modules/operator-unmanaged-storage-noobaa.adoc
  modules/operator-unmanaged-storage.adoc
  modules/operator-volume-size-overrides.adoc
  modules/proc_container-security-operator-setup.adoc
  red_hat_quay_operator_features/master.adoc
Labels: redhat-3.9

#676 Adds CORS GCP procedure
  modules/builders-virtual-environment.adoc
Labels: redhat-3.8, redhat-3.9

#692 Moves config content to features
  deploy_red_hat_quay_operator/master.adoc
  modules/operator-quayregistry-api.adoc
  red_hat_quay_operator_features/master.adoc
Labels: redhat-3.9

#693 Removed duplicate configuration parameter
  modules/config-fields-scanner.adoc
Labels: redhat-3.8, redhat-3.9

#695 changes to modules/clair-openshift-airgap-database.adoc, fixed indentation
  modules/clair-openshift-airgap-database-standalone.adoc
  modules/clair-openshift-airgap-database.adoc
Labels: redhat-3.8, redhat-3.9

#696 Updates airgapped clair docs
  modules/clair-openshift-airgap-database-standalone.adoc
  modules/clair-openshift-airgap-database.adoc
Labels: redhat-3.8

#702 Updates clair key cert file names
  modules/configuring-custom-clair-database.adoc
Labels: redhat-3.8, redhat-3.9

#703 Updates link
  modules/ssl-trust-ca-system.adoc
Labels: redhat-3.8, redhat-3.9
